/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.records;


import com.jvmrally.lambda.db.enums.AuditAction;
import com.jvmrally.lambda.db.tables.Audit;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditRecord extends UpdatableRecordImpl<AuditRecord> implements Record7<Integer, Long, AuditAction, Long, String, OffsetDateTime, Long> {

    private static final long serialVersionUID = -548292117;

    /**
     * Setter for <code>audit.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>audit.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>audit.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>audit.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>audit.mod_action</code>.
     */
    public void setModAction(AuditAction value) {
        set(2, value);
    }

    /**
     * Getter for <code>audit.mod_action</code>.
     */
    public AuditAction getModAction() {
        return (AuditAction) get(2);
    }

    /**
     * Setter for <code>audit.target_user</code>.
     */
    public void setTargetUser(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>audit.target_user</code>.
     */
    public Long getTargetUser() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>audit.reason</code>.
     */
    public void setReason(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>audit.reason</code>.
     */
    public String getReason() {
        return (String) get(4);
    }

    /**
     * Setter for <code>audit.created</code>.
     */
    public void setCreated(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>audit.created</code>.
     */
    public OffsetDateTime getCreated() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>audit.guild_id</code>.
     */
    public void setGuildId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>audit.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Long, AuditAction, Long, String, OffsetDateTime, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Long, AuditAction, Long, String, OffsetDateTime, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Audit.AUDIT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Audit.AUDIT.USER_ID;
    }

    @Override
    public Field<AuditAction> field3() {
        return Audit.AUDIT.MOD_ACTION;
    }

    @Override
    public Field<Long> field4() {
        return Audit.AUDIT.TARGET_USER;
    }

    @Override
    public Field<String> field5() {
        return Audit.AUDIT.REASON;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Audit.AUDIT.CREATED;
    }

    @Override
    public Field<Long> field7() {
        return Audit.AUDIT.GUILD_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public AuditAction component3() {
        return getModAction();
    }

    @Override
    public Long component4() {
        return getTargetUser();
    }

    @Override
    public String component5() {
        return getReason();
    }

    @Override
    public OffsetDateTime component6() {
        return getCreated();
    }

    @Override
    public Long component7() {
        return getGuildId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public AuditAction value3() {
        return getModAction();
    }

    @Override
    public Long value4() {
        return getTargetUser();
    }

    @Override
    public String value5() {
        return getReason();
    }

    @Override
    public OffsetDateTime value6() {
        return getCreated();
    }

    @Override
    public Long value7() {
        return getGuildId();
    }

    @Override
    public AuditRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AuditRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public AuditRecord value3(AuditAction value) {
        setModAction(value);
        return this;
    }

    @Override
    public AuditRecord value4(Long value) {
        setTargetUser(value);
        return this;
    }

    @Override
    public AuditRecord value5(String value) {
        setReason(value);
        return this;
    }

    @Override
    public AuditRecord value6(OffsetDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public AuditRecord value7(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public AuditRecord values(Integer value1, Long value2, AuditAction value3, Long value4, String value5, OffsetDateTime value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditRecord
     */
    public AuditRecord() {
        super(Audit.AUDIT);
    }

    /**
     * Create a detached, initialised AuditRecord
     */
    public AuditRecord(Integer id, Long userId, AuditAction modAction, Long targetUser, String reason, OffsetDateTime created, Long guildId) {
        super(Audit.AUDIT);

        set(0, id);
        set(1, userId);
        set(2, modAction);
        set(3, targetUser);
        set(4, reason);
        set(5, created);
        set(6, guildId);
    }
}
