/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.records;


import com.jvmrally.lambda.db.tables.Ban;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BanRecord extends UpdatableRecordImpl<BanRecord> implements Record3<Long, Long, Long> {

    private static final long serialVersionUID = -2084574360;

    /**
     * Setter for <code>ban.userid</code>.
     */
    public void setUserid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ban.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ban.ban_expiry</code>.
     */
    public void setBanExpiry(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ban.ban_expiry</code>.
     */
    public Long getBanExpiry() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ban.guild_id</code>.
     */
    public void setGuildId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ban.guild_id</code>.
     */
    public Long getGuildId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Long, Long, Long> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Long, Long, Long> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Ban.BAN.USERID;
    }

    @Override
    public Field<Long> field2() {
        return Ban.BAN.BAN_EXPIRY;
    }

    @Override
    public Field<Long> field3() {
        return Ban.BAN.GUILD_ID;
    }

    @Override
    public Long component1() {
        return getUserid();
    }

    @Override
    public Long component2() {
        return getBanExpiry();
    }

    @Override
    public Long component3() {
        return getGuildId();
    }

    @Override
    public Long value1() {
        return getUserid();
    }

    @Override
    public Long value2() {
        return getBanExpiry();
    }

    @Override
    public Long value3() {
        return getGuildId();
    }

    @Override
    public BanRecord value1(Long value) {
        setUserid(value);
        return this;
    }

    @Override
    public BanRecord value2(Long value) {
        setBanExpiry(value);
        return this;
    }

    @Override
    public BanRecord value3(Long value) {
        setGuildId(value);
        return this;
    }

    @Override
    public BanRecord values(Long value1, Long value2, Long value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BanRecord
     */
    public BanRecord() {
        super(Ban.BAN);
    }

    /**
     * Create a detached, initialised BanRecord
     */
    public BanRecord(Long userid, Long banExpiry, Long guildId) {
        super(Ban.BAN);

        set(0, userid);
        set(1, banExpiry);
        set(2, guildId);
    }
}
