/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.records;


import com.jvmrally.lambda.db.tables.DisabledCommands;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisabledCommandsRecord extends UpdatableRecordImpl<DisabledCommandsRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = -2069702494;

    /**
     * Setter for <code>disabled_commands.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>disabled_commands.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>disabled_commands.guild_id</code>.
     */
    public void setGuildId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>disabled_commands.guild_id</code>.
     */
    public String getGuildId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>disabled_commands.command_name</code>.
     */
    public void setCommandName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>disabled_commands.command_name</code>.
     */
    public String getCommandName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DisabledCommands.DISABLED_COMMANDS.ID;
    }

    @Override
    public Field<String> field2() {
        return DisabledCommands.DISABLED_COMMANDS.GUILD_ID;
    }

    @Override
    public Field<String> field3() {
        return DisabledCommands.DISABLED_COMMANDS.COMMAND_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getGuildId();
    }

    @Override
    public String component3() {
        return getCommandName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getGuildId();
    }

    @Override
    public String value3() {
        return getCommandName();
    }

    @Override
    public DisabledCommandsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DisabledCommandsRecord value2(String value) {
        setGuildId(value);
        return this;
    }

    @Override
    public DisabledCommandsRecord value3(String value) {
        setCommandName(value);
        return this;
    }

    @Override
    public DisabledCommandsRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DisabledCommandsRecord
     */
    public DisabledCommandsRecord() {
        super(DisabledCommands.DISABLED_COMMANDS);
    }

    /**
     * Create a detached, initialised DisabledCommandsRecord
     */
    public DisabledCommandsRecord(Integer id, String guildId, String commandName) {
        super(DisabledCommands.DISABLED_COMMANDS);

        set(0, id);
        set(1, guildId);
        set(2, commandName);
    }
}
