/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import com.jvmrally.lambda.db.enums.AuditAction;

import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Audit implements Serializable {

    private static final long serialVersionUID = 684758469;

    private Integer        id;
    private Long           userId;
    private AuditAction    modAction;
    private Long           targetUser;
    private String         reason;
    private OffsetDateTime created;

    public Audit() {}

    public Audit(Audit value) {
        this.id = value.id;
        this.userId = value.userId;
        this.modAction = value.modAction;
        this.targetUser = value.targetUser;
        this.reason = value.reason;
        this.created = value.created;
    }

    public Audit(
        Integer        id,
        Long           userId,
        AuditAction    modAction,
        Long           targetUser,
        String         reason,
        OffsetDateTime created
    ) {
        this.id = id;
        this.userId = userId;
        this.modAction = modAction;
        this.targetUser = targetUser;
        this.reason = reason;
        this.created = created;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public AuditAction getModAction() {
        return this.modAction;
    }

    public void setModAction(AuditAction modAction) {
        this.modAction = modAction;
    }

    public Long getTargetUser() {
        return this.targetUser;
    }

    public void setTargetUser(Long targetUser) {
        this.targetUser = targetUser;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public OffsetDateTime getCreated() {
        return this.created;
    }

    public void setCreated(OffsetDateTime created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Audit (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(modAction);
        sb.append(", ").append(targetUser);
        sb.append(", ").append(reason);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
}
