/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DisabledCommands implements Serializable {

    private static final long serialVersionUID = -818511418;

    private Integer id;
    private String  guildId;
    private String  commandName;

    public DisabledCommands() {}

    public DisabledCommands(DisabledCommands value) {
        this.id = value.id;
        this.guildId = value.guildId;
        this.commandName = value.commandName;
    }

    public DisabledCommands(
        Integer id,
        String  guildId,
        String  commandName
    ) {
        this.id = id;
        this.guildId = guildId;
        this.commandName = commandName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGuildId() {
        return this.guildId;
    }

    public void setGuildId(String guildId) {
        this.guildId = guildId;
    }

    public String getCommandName() {
        return this.commandName;
    }

    public void setCommandName(String commandName) {
        this.commandName = commandName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DisabledCommands (");

        sb.append(id);
        sb.append(", ").append(guildId);
        sb.append(", ").append(commandName);

        sb.append(")");
        return sb.toString();
    }
}
