/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DmTimeouts implements Serializable {

    private static final long serialVersionUID = 369908567;

    private Long userid;
    private Long lastMessageTime;

    public DmTimeouts() {}

    public DmTimeouts(DmTimeouts value) {
        this.userid = value.userid;
        this.lastMessageTime = value.lastMessageTime;
    }

    public DmTimeouts(
        Long userid,
        Long lastMessageTime
    ) {
        this.userid = userid;
        this.lastMessageTime = lastMessageTime;
    }

    public Long getUserid() {
        return this.userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Long getLastMessageTime() {
        return this.lastMessageTime;
    }

    public void setLastMessageTime(Long lastMessageTime) {
        this.lastMessageTime = lastMessageTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DmTimeouts (");

        sb.append(userid);
        sb.append(", ").append(lastMessageTime);

        sb.append(")");
        return sb.toString();
    }
}
