/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jeps implements Serializable {

    private static final long serialVersionUID = 1841882612;

    private Integer id;
    private String  title;
    private String  jepType;
    private String  jepStatus;
    private String  release;
    private String  component;
    private String  jepUrl;

    public Jeps() {}

    public Jeps(Jeps value) {
        this.id = value.id;
        this.title = value.title;
        this.jepType = value.jepType;
        this.jepStatus = value.jepStatus;
        this.release = value.release;
        this.component = value.component;
        this.jepUrl = value.jepUrl;
    }

    public Jeps(
        Integer id,
        String  title,
        String  jepType,
        String  jepStatus,
        String  release,
        String  component,
        String  jepUrl
    ) {
        this.id = id;
        this.title = title;
        this.jepType = jepType;
        this.jepStatus = jepStatus;
        this.release = release;
        this.component = component;
        this.jepUrl = jepUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getJepType() {
        return this.jepType;
    }

    public void setJepType(String jepType) {
        this.jepType = jepType;
    }

    public String getJepStatus() {
        return this.jepStatus;
    }

    public void setJepStatus(String jepStatus) {
        this.jepStatus = jepStatus;
    }

    public String getRelease() {
        return this.release;
    }

    public void setRelease(String release) {
        this.release = release;
    }

    public String getComponent() {
        return this.component;
    }

    public void setComponent(String component) {
        this.component = component;
    }

    public String getJepUrl() {
        return this.jepUrl;
    }

    public void setJepUrl(String jepUrl) {
        this.jepUrl = jepUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Jeps (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(jepType);
        sb.append(", ").append(jepStatus);
        sb.append(", ").append(release);
        sb.append(", ").append(component);
        sb.append(", ").append(jepUrl);

        sb.append(")");
        return sb.toString();
    }
}
