/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jeps implements Serializable {

    private static final long serialVersionUID = 940670914;

    private Integer id;
    private String  title;
    private String  jepType;
    private String  jepStatus;
    private String  release;
    private String  component;
    private String  jepUrl;

    public Jeps() {}

    public Jeps(Jeps value) {
        this.id = value.id;
        this.title = value.title;
        this.jepType = value.jepType;
        this.jepStatus = value.jepStatus;
        this.release = value.release;
        this.component = value.component;
        this.jepUrl = value.jepUrl;
    }

    public Jeps(
        Integer id,
        String  title,
        String  jepType,
        String  jepStatus,
        String  release,
        String  component,
        String  jepUrl
    ) {
        this.id = id;
        this.title = title;
        this.jepType = jepType;
        this.jepStatus = jepStatus;
        this.release = release;
        this.component = component;
        this.jepUrl = jepUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getJepType() {
        return this.jepType;
    }

    public void setJepType(String jepType) {
        this.jepType = jepType;
    }

    public String getJepStatus() {
        return this.jepStatus;
    }

    public void setJepStatus(String jepStatus) {
        this.jepStatus = jepStatus;
    }

    public String getRelease() {
        return this.release;
    }

    public void setRelease(String release) {
        this.release = release;
    }

    public String getComponent() {
        return this.component;
    }

    public void setComponent(String component) {
        this.component = component;
    }

    public String getJepUrl() {
        return this.jepUrl;
    }

    public void setJepUrl(String jepUrl) {
        this.jepUrl = jepUrl;
    }

    @Override
    public String toString() {
        return new StringBuilder("Jeps (")
                        .append(id)
                        .append(", ").append(title)
                        .append(", ").append(jepType)
                        .append(", ").append(jepStatus)
                        .append(", ").append(release)
                        .append(", ").append(component)
                        .append(", ").append(jepUrl).toString();
    }
}
