/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mute implements Serializable {

    private static final long serialVersionUID = -1679031731;

    private Long userid;
    private Long muteExpiry;

    public Mute() {}

    public Mute(Mute value) {
        this.userid = value.userid;
        this.muteExpiry = value.muteExpiry;
    }

    public Mute(
        Long userid,
        Long muteExpiry
    ) {
        this.userid = userid;
        this.muteExpiry = muteExpiry;
    }

    public Long getUserid() {
        return this.userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Long getMuteExpiry() {
        return this.muteExpiry;
    }

    public void setMuteExpiry(Long muteExpiry) {
        this.muteExpiry = muteExpiry;
    }

    @Override
    public String toString() {
        return new StringBuilder("Mute (")
            .append(userid)
            .append(", ")
            .append(muteExpiry)
            .append(")").toString();
    }
}
