/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mute implements Serializable {

    private static final long serialVersionUID = 310001637;

    private Long userid;
    private Long muteExpiry;
    private Long guildId;

    public Mute() {}

    public Mute(Mute value) {
        this.userid = value.userid;
        this.muteExpiry = value.muteExpiry;
        this.guildId = value.guildId;
    }

    public Mute(
        Long userid,
        Long muteExpiry,
        Long guildId
    ) {
        this.userid = userid;
        this.muteExpiry = muteExpiry;
        this.guildId = guildId;
    }

    public Long getUserid() {
        return this.userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Long getMuteExpiry() {
        return this.muteExpiry;
    }

    public void setMuteExpiry(Long muteExpiry) {
        this.muteExpiry = muteExpiry;
    }

    public Long getGuildId() {
        return this.guildId;
    }

    public void setGuildId(Long guildId) {
        this.guildId = guildId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Mute (");

        sb.append(userid);
        sb.append(", ").append(muteExpiry);
        sb.append(", ").append(guildId);

        sb.append(")");
        return sb.toString();
    }
}
