/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tags implements Serializable {

    private static final long serialVersionUID = 1082956081;

    private Integer        id;
    private String         tagname;
    private String         content;
    private OffsetDateTime updatedAt;
    private Long           guildId;

    public Tags() {}

    public Tags(Tags value) {
        this.id = value.id;
        this.tagname = value.tagname;
        this.content = value.content;
        this.updatedAt = value.updatedAt;
        this.guildId = value.guildId;
    }

    public Tags(
        Integer        id,
        String         tagname,
        String         content,
        OffsetDateTime updatedAt,
        Long           guildId
    ) {
        this.id = id;
        this.tagname = tagname;
        this.content = content;
        this.updatedAt = updatedAt;
        this.guildId = guildId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTagname() {
        return this.tagname;
    }

    public void setTagname(String tagname) {
        this.tagname = tagname;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public Long getGuildId() {
        return this.guildId;
    }

    public void setGuildId(Long guildId) {
        this.guildId = guildId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Tags (");

        sb.append(id);
        sb.append(", ").append(tagname);
        sb.append(", ").append(content);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(guildId);

        sb.append(")");
        return sb.toString();
    }
}
