/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db.enums;


import com.jvmrally.lambda.db.DefaultSchema;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum AuditAction implements EnumType {

    BANNED("BANNED"),

    UNBANNED("UNBANNED"),

    WARNED("WARNED"),

    MUTED("MUTED"),

    UNMUTED("UNMUTED"),

    GIVE_ROLE("GIVE_ROLE"),

    REMOVE_ROLE("REMOVE_ROLE"),

    CREATED_TAG("CREATED_TAG"),

    EDITED_TAG("EDITED_TAG"),

    DELETED_TAG("DELETED_TAG");

    private final String literal;

    private AuditAction(String literal) {
        this.literal = literal;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return getSchema() == null ? null : getSchema().getCatalog();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getName() {
        return "audit_action";
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String getLiteral() {
        return literal;
    }
}
