/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db;


import com.jvmrally.lambda.db.tables.Audit;
import com.jvmrally.lambda.db.tables.Ban;
import com.jvmrally.lambda.db.tables.DmTimeouts;
import com.jvmrally.lambda.db.tables.Jeps;
import com.jvmrally.lambda.db.tables.Mute;
import com.jvmrally.lambda.db.tables.Tags;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index AUDIT_PKEY = Indexes0.AUDIT_PKEY;
    public static final Index BAN_PKEY = Indexes0.BAN_PKEY;
    public static final Index DM_TIMEOUTS_PKEY = Indexes0.DM_TIMEOUTS_PKEY;
    public static final Index JEPS_PKEY = Indexes0.JEPS_PKEY;
    public static final Index JEPS_TITLE_KEY = Indexes0.JEPS_TITLE_KEY;
    public static final Index MUTE_PKEY = Indexes0.MUTE_PKEY;
    public static final Index TAGS_PKEY = Indexes0.TAGS_PKEY;
    public static final Index TAGS_TAGNAME_KEY = Indexes0.TAGS_TAGNAME_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index AUDIT_PKEY = Internal.createIndex("audit_pkey", Audit.AUDIT, new OrderField[] { Audit.AUDIT.ID }, true);
        public static Index BAN_PKEY = Internal.createIndex("ban_pkey", Ban.BAN, new OrderField[] { Ban.BAN.USERID }, true);
        public static Index DM_TIMEOUTS_PKEY = Internal.createIndex("dm_timeouts_pkey", DmTimeouts.DM_TIMEOUTS, new OrderField[] { DmTimeouts.DM_TIMEOUTS.USERID }, true);
        public static Index JEPS_PKEY = Internal.createIndex("jeps_pkey", Jeps.JEPS, new OrderField[] { Jeps.JEPS.ID }, true);
        public static Index JEPS_TITLE_KEY = Internal.createIndex("jeps_title_key", Jeps.JEPS, new OrderField[] { Jeps.JEPS.TITLE }, true);
        public static Index MUTE_PKEY = Internal.createIndex("mute_pkey", Mute.MUTE, new OrderField[] { Mute.MUTE.USERID }, true);
        public static Index TAGS_PKEY = Internal.createIndex("tags_pkey", Tags.TAGS, new OrderField[] { Tags.TAGS.ID }, true);
        public static Index TAGS_TAGNAME_KEY = Internal.createIndex("tags_tagname_key", Tags.TAGS, new OrderField[] { Tags.TAGS.TAGNAME }, true);
    }
}
