/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db;


import com.jvmrally.lambda.db.tables.DmTimeouts;
import javax.annotation.Generated;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.11.11"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DM_TIMEOUTS_PKEY = Indexes0.DM_TIMEOUTS_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DM_TIMEOUTS_PKEY = Internal.createIndex("dm_timeouts_pkey",
                DmTimeouts.DM_TIMEOUTS, new OrderField[] {DmTimeouts.DM_TIMEOUTS.USERID}, true);
    }
}
