/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db;


import com.jvmrally.lambda.db.tables.Audit;
import com.jvmrally.lambda.db.tables.Ban;
import com.jvmrally.lambda.db.tables.DmTimeouts;
import com.jvmrally.lambda.db.tables.Mute;
import com.jvmrally.lambda.db.tables.Tags;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>audit</code>.
     */
    public static final Audit AUDIT = com.jvmrally.lambda.db.tables.Audit.AUDIT;

    /**
     * The table <code>ban</code>.
     */
    public static final Ban BAN = com.jvmrally.lambda.db.tables.Ban.BAN;

    /**
     * The table <code>dm_timeouts</code>.
     */
    public static final DmTimeouts DM_TIMEOUTS = com.jvmrally.lambda.db.tables.DmTimeouts.DM_TIMEOUTS;

    /**
     * The table <code>mute</code>.
     */
    public static final Mute MUTE = com.jvmrally.lambda.db.tables.Mute.MUTE;

    /**
     * The table <code>tags</code>.
     */
    public static final Tags TAGS = com.jvmrally.lambda.db.tables.Tags.TAGS;
}
