/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db;


import com.jvmrally.lambda.db.tables.DmTimeouts;
import javax.annotation.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.11.11"},
        comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>dm_timeouts</code>.
     */
    public static final DmTimeouts DM_TIMEOUTS =
            com.jvmrally.lambda.db.tables.DmTimeouts.DM_TIMEOUTS;
}
