/*
 * This file is generated by jOOQ.
 */
package com.jvmrally.lambda.db;


import com.jvmrally.lambda.db.tables.Audit;
import com.jvmrally.lambda.db.tables.Ban;
import com.jvmrally.lambda.db.tables.DisabledCommands;
import com.jvmrally.lambda.db.tables.DmTimeouts;
import com.jvmrally.lambda.db.tables.Jeps;
import com.jvmrally.lambda.db.tables.Mute;
import com.jvmrally.lambda.db.tables.Tags;


/**
 * Convenience access to all tables in 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>audit</code>.
     */
    public static final Audit AUDIT = Audit.AUDIT;

    /**
     * The table <code>ban</code>.
     */
    public static final Ban BAN = Ban.BAN;

    /**
     * The table <code>disabled_commands</code>.
     */
    public static final DisabledCommands DISABLED_COMMANDS = DisabledCommands.DISABLED_COMMANDS;

    /**
     * The table <code>dm_timeouts</code>.
     */
    public static final DmTimeouts DM_TIMEOUTS = DmTimeouts.DM_TIMEOUTS;

    /**
     * The table <code>jeps</code>.
     */
    public static final Jeps JEPS = Jeps.JEPS;

    /**
     * The table <code>mute</code>.
     */
    public static final Mute MUTE = Mute.MUTE;

    /**
     * The table <code>tags</code>.
     */
    public static final Tags TAGS = Tags.TAGS;
}
